create extension if not exists pgcrypto;

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  class text not null,
  teacher text not null,
  subject text not null,
  term text not null,
  year text not null,
  stream text not null default 'A',
  count integer not null default 0,
  status text not null default 'Pending Admin',
  date text not null,
  rows jsonb not null default '[]'::jsonb
);

alter table public.results enable row level security;

create policy "Public read is allowed for results" on public.results
for select using (true);

create policy "Public insert is allowed for results" on public.results
for insert with check (true);

create policy "Public update is allowed for results" on public.results
for update using (true) with check (true);

create policy "Public delete is allowed for results" on public.results
for delete using (true);
